apiVersion: v1
items:
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    creationTimestamp: "2025-11-23T03:15:00Z"
    name: default
    namespace: kube-public
    resourceVersion: "401"
    uid: ea0f2a10-29ab-4647-9c05-9eba25b05c74
kind: List
metadata:
  resourceVersion: ""
