apiVersion: v1
items:
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    creationTimestamp: "2025-11-23T03:14:59Z"
    name: default
    namespace: default
    resourceVersion: "399"
    uid: 22dc6a13-888e-4448-9c8e-f29171b59ca5
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"v1","kind":"ServiceAccount","metadata":{"annotations":{},"name":"kubesentry-controller","namespace":"default"}}
    creationTimestamp: "2025-11-28T02:42:02Z"
    name: kubesentry-controller
    namespace: default
    resourceVersion: "1131467"
    uid: 9ed2fb01-bcd0-41e6-bd2c-ddfd6cc87273
kind: List
metadata:
  resourceVersion: ""
