apiVersion: v1
items:
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    creationTimestamp: "2025-11-23T03:15:00Z"
    name: default
    namespace: kube-node-lease
    resourceVersion: "400"
    uid: 1ea65674-bb6c-441f-ad5b-07a1099b2bd3
kind: List
metadata:
  resourceVersion: ""
