apiVersion: v1
items:
- apiVersion: rbac.authorization.k8s.io/v1
  kind: RoleBinding
  metadata:
    annotations:
      meta.helm.sh/release-name: loki-stack
      meta.helm.sh/release-namespace: loki
    creationTimestamp: "2025-11-24T22:36:11Z"
    labels:
      app: loki
      app.kubernetes.io/managed-by: Helm
      chart: loki-2.16.0
      heritage: Helm
      release: loki-stack
    name: loki-stack
    namespace: loki
    resourceVersion: "413697"
    uid: 313d94d0-848a-4992-a2bb-55db6bcbd8e5
  roleRef:
    apiGroup: rbac.authorization.k8s.io
    kind: Role
    name: loki-stack
  subjects:
  - kind: ServiceAccount
    name: loki-stack
kind: List
metadata:
  resourceVersion: ""
