apiVersion: v1
items:
- apiVersion: rbac.authorization.k8s.io/v1
  kind: Role
  metadata:
    annotations:
      meta.helm.sh/release-name: loki-stack
      meta.helm.sh/release-namespace: loki
    creationTimestamp: "2025-11-24T22:36:11Z"
    labels:
      app: loki
      app.kubernetes.io/managed-by: Helm
      chart: loki-2.16.0
      heritage: Helm
      release: loki-stack
    name: loki-stack
    namespace: loki
    resourceVersion: "413696"
    uid: 10478637-c9d4-44b4-8f75-e9a057d2d68b
  rules:
  - apiGroups:
    - extensions
    resourceNames:
    - loki-stack
    resources:
    - podsecuritypolicies
    verbs:
    - use
kind: List
metadata:
  resourceVersion: ""
