apiVersion: v1
items:
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    creationTimestamp: "2025-11-24T22:31:03Z"
    name: default
    namespace: loki
    resourceVersion: "412636"
    uid: 5aa7ce7c-4a34-40a9-851f-6d7ff4cdab87
- apiVersion: v1
  automountServiceAccountToken: true
  kind: ServiceAccount
  metadata:
    annotations:
      meta.helm.sh/release-name: loki-stack
      meta.helm.sh/release-namespace: loki
    creationTimestamp: "2025-11-24T22:36:11Z"
    labels:
      app: loki
      app.kubernetes.io/managed-by: Helm
      chart: loki-2.16.0
      heritage: Helm
      release: loki-stack
    name: loki-stack
    namespace: loki
    resourceVersion: "413688"
    uid: 61c95151-4845-445e-bfad-e63384d8b0cf
- apiVersion: v1
  automountServiceAccountToken: true
  kind: ServiceAccount
  metadata:
    annotations:
      meta.helm.sh/release-name: loki-stack
      meta.helm.sh/release-namespace: loki
    creationTimestamp: "2025-11-24T22:36:11Z"
    labels:
      app.kubernetes.io/instance: loki-stack
      app.kubernetes.io/managed-by: Helm
      app.kubernetes.io/name: promtail
      app.kubernetes.io/version: 3.5.1
      helm.sh/chart: promtail-6.17.0
    name: loki-stack-promtail
    namespace: loki
    resourceVersion: "413689"
    uid: b6fc02b8-43b5-4931-8749-130096675c02
kind: List
metadata:
  resourceVersion: ""
