apiVersion: v1
items:
- apiVersion: apps/v1
  kind: DaemonSet
  metadata:
    annotations:
      deprecated.daemonset.template.generation: "6"
      meta.helm.sh/release-name: tetragon
      meta.helm.sh/release-namespace: kubesentry
    creationTimestamp: "2025-11-23T17:05:51Z"
    generation: 6
    labels:
      app.kubernetes.io/component: agent
      app.kubernetes.io/instance: tetragon
      app.kubernetes.io/managed-by: Helm
      app.kubernetes.io/name: tetragon
      app.kubernetes.io/part-of: tetragon
      app.kubernetes.io/version: 1.6.0
      helm.sh/chart: tetragon-1.6.0
    name: tetragon
    namespace: kubesentry
    resourceVersion: "404305"
    uid: e97074fe-61ed-41d2-a1c2-2bb5f65d5de4
  spec:
    revisionHistoryLimit: 10
    selector:
      matchLabels:
        app.kubernetes.io/instance: tetragon
        app.kubernetes.io/name: tetragon
    template:
      metadata:
        annotations:
          checksum/configmap: 0ca7f1de64a5350424c132e5bd0e1ee82f20e45b012096c68ba0f28592b4bb14
        labels:
          app.kubernetes.io/component: agent
          app.kubernetes.io/instance: tetragon
          app.kubernetes.io/managed-by: Helm
          app.kubernetes.io/name: tetragon
          app.kubernetes.io/part-of: tetragon
          app.kubernetes.io/version: 1.6.0
          helm.sh/chart: tetragon-1.6.0
      spec:
        containers:
        - args:
          - /var/run/cilium/tetragon/tetragon.log
          command:
          - hubble-export-stdout
          image: quay.io/cilium/hubble-export-stdout:v1.1.0
          imagePullPolicy: IfNotPresent
          name: export-stdout
          resources: {}
          securityContext: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: FallbackToLogsOnError
          volumeMounts:
          - mountPath: /var/run/cilium/tetragon
            name: export-logs
        - args:
          - --config-dir=/etc/tetragon/tetragon.conf.d/
          env:
          - name: NODE_NAME
            valueFrom:
              fieldRef:
                apiVersion: v1
                fieldPath: spec.nodeName
          image: quay.io/cilium/tetragon:v1.6.0
          imagePullPolicy: IfNotPresent
          livenessProbe:
            failureThreshold: 3
            grpc:
              port: 6789
              service: liveness
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 60
          name: tetragon
          resources:
            limits:
              cpu: 500m
              memory: 512Mi
            requests:
              cpu: 100m
              memory: 128Mi
          securityContext:
            privileged: true
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: FallbackToLogsOnError
          volumeMounts:
          - mountPath: /etc/tetragon/tetragon.conf.d/
            name: tetragon-config
            readOnly: true
          - mountPath: /sys/fs/bpf
            mountPropagation: Bidirectional
            name: bpf-maps
          - mountPath: /var/run/cilium
            name: cilium-run
          - mountPath: /var/run/cilium/tetragon
            name: export-logs
          - mountPath: /procRoot
            name: host-proc
        dnsPolicy: Default
        hostNetwork: true
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: {}
        serviceAccount: tetragon
        serviceAccountName: tetragon
        terminationGracePeriodSeconds: 1
        tolerations:
        - operator: Exists
        volumes:
        - hostPath:
            path: /var/run/cilium
            type: DirectoryOrCreate
          name: cilium-run
        - hostPath:
            path: /var/run/cilium/tetragon
            type: DirectoryOrCreate
          name: export-logs
        - configMap:
            defaultMode: 420
            name: tetragon-config
          name: tetragon-config
        - hostPath:
            path: /sys/fs/bpf
            type: DirectoryOrCreate
          name: bpf-maps
        - hostPath:
            path: /proc
            type: Directory
          name: host-proc
    updateStrategy:
      rollingUpdate:
        maxSurge: 0
        maxUnavailable: 1
      type: RollingUpdate
  status:
    currentNumberScheduled: 4
    desiredNumberScheduled: 4
    numberAvailable: 4
    numberMisscheduled: 0
    numberReady: 4
    observedGeneration: 6
    updatedNumberScheduled: 4
kind: List
metadata:
  resourceVersion: ""
