apiVersion: v1
items:
- apiVersion: rbac.authorization.k8s.io/v1
  kind: Role
  metadata:
    annotations:
      meta.helm.sh/release-name: tetragon
      meta.helm.sh/release-namespace: kubesentry
    creationTimestamp: "2025-11-23T17:05:51Z"
    labels:
      app.kubernetes.io/component: agent
      app.kubernetes.io/instance: tetragon
      app.kubernetes.io/managed-by: Helm
      app.kubernetes.io/name: tetragon
      app.kubernetes.io/part-of: tetragon
      app.kubernetes.io/version: 1.6.0
      helm.sh/chart: tetragon-1.6.0
    name: tetragon
    namespace: kubesentry
    resourceVersion: "132004"
    uid: 006c0822-a2fd-40e2-9c91-f6c57c2e666b
  rules: null
kind: List
metadata:
  resourceVersion: ""
