apiVersion: v1
items:
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    creationTimestamp: "2025-11-23T04:34:45Z"
    name: default
    namespace: kubesentry
    resourceVersion: "13880"
    uid: ea3b1e08-e259-46d2-9b9c-b53e5acc78c8
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    annotations:
      meta.helm.sh/release-name: tetragon
      meta.helm.sh/release-namespace: kubesentry
    creationTimestamp: "2025-11-23T17:05:51Z"
    labels:
      app.kubernetes.io/component: agent
      app.kubernetes.io/instance: tetragon
      app.kubernetes.io/managed-by: Helm
      app.kubernetes.io/name: tetragon
      app.kubernetes.io/part-of: tetragon
      app.kubernetes.io/version: 1.6.0
      helm.sh/chart: tetragon-1.6.0
    name: tetragon
    namespace: kubesentry
    resourceVersion: "131996"
    uid: b51d0060-37c1-41a0-97ab-4df3a29909bf
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    annotations:
      meta.helm.sh/release-name: tetragon
      meta.helm.sh/release-namespace: kubesentry
    creationTimestamp: "2025-11-23T17:05:51Z"
    labels:
      app.kubernetes.io/component: operator
      app.kubernetes.io/instance: tetragon
      app.kubernetes.io/managed-by: Helm
      app.kubernetes.io/name: tetragon-operator
      app.kubernetes.io/part-of: tetragon
      app.kubernetes.io/version: 1.6.0
      helm.sh/chart: tetragon-1.6.0
    name: tetragon-operator-service-account
    namespace: kubesentry
    resourceVersion: "131997"
    uid: a5cdfa91-af62-4639-aabb-139e213b68cf
kind: List
metadata:
  resourceVersion: ""
