apiVersion: v1
items:
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    creationTimestamp: "2025-11-23T03:58:10Z"
    name: default
    namespace: kube-state-metrics
    resourceVersion: "8102"
    uid: f338a2e8-155c-4a9b-a9b0-af0d5410bed8
- apiVersion: v1
  automountServiceAccountToken: true
  kind: ServiceAccount
  metadata:
    annotations:
      meta.helm.sh/release-name: kube-state-metrics
      meta.helm.sh/release-namespace: kube-state-metrics
    creationTimestamp: "2025-11-23T03:58:10Z"
    labels:
      app.kubernetes.io/component: metrics
      app.kubernetes.io/instance: kube-state-metrics
      app.kubernetes.io/managed-by: Helm
      app.kubernetes.io/name: kube-state-metrics
      app.kubernetes.io/part-of: kube-state-metrics
      app.kubernetes.io/version: 2.13.0
      helm.sh/chart: kube-state-metrics-5.25.1
    name: kube-state-metrics
    namespace: kube-state-metrics
    resourceVersion: "8105"
    uid: e57f1073-7c43-40c0-99e7-60b2a90e8816
kind: List
metadata:
  resourceVersion: ""
