apiVersion: v1
items:
- apiVersion: v1
  data:
    ca.crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURpakNDQW5LZ0F3SUJBZ0lSQUxSdGo3OVROakZGeDBZYWdyTWEzem93RFFZSktvWklodmNOQVFFTEJRQXcKVHpFTE1Ba0dBMVVFQmhNQ1ZWTXhGakFVQmdOVkJBY1REVk5oYmlCR2NtRnVZMmx6WTI4eEV6QVJCZ05WQkFvVApDa3QxWW1WeWJtVjBaWE14RXpBUkJnTlZCQU1UQ2t0MVltVnlibVYwWlhNd0hoY05NalV4TVRJek1ETXhOREF5CldoY05NekF4TVRJek1ETXhOREF5V2pCUE1Rc3dDUVlEVlFRR0V3SlZVekVXTUJRR0ExVUVCeE1OVTJGdUlFWnkKWVc1amFYTmpiekVUTUJFR0ExVUVDaE1LUzNWaVpYSnVaWFJsY3pFVE1CRUdBMVVFQXhNS1MzVmlaWEp1WlhSbApjekNDQVNJd0RRWUpLb1pJaHZjTkFRRUJCUUFEZ2dFUEFEQ0NBUW9DZ2dFQkFLSnNqNmVXNlZBTHMyR3JmYlZDCkxhOHNJQ3A2MkNhaFlOQzhvcnVIUWk5N1JVaS96Rmo3ZzdGekFHWUNxVWxHY0J2cllOcGVWeDRWZUsycHFraUMKYlBTaWtVbFJKWkpSeTUrZndHWEtZbkVTTko5NFBvZkg1MS9DMCs3UkJsUFdZWUZaSitHMy9hSHYwL3RGeW5PVwphT3hHOXd1Q0R4K1ViV3VWSFFDL3o3WnJUUm1kTUdUSXNDcktGbWp1N3dZSnZYRjd0UThoK1k2c09MYTczUGN1CkluajY5cnBhZzhkMGRWVXZKQ1hWd1Y3WkhBaUpXc3doVzJ4alVHNDRlNWs4cnJBcmYyUEo2VkhDdFZNdWs3eTcKQTRPL0g0aHJVUVJ3aHpxSDNCQnBBZG82MmNVM3g2MFhucTFOZ1pjdjliYzNDM2pLVkVYdVVtd3pXRDNZOFFNTgppQWtDQXdFQUFhTmhNRjh3RGdZRFZSMFBBUUgvQkFRREFnS0VNQjBHQTFVZEpRUVdNQlFHQ0NzR0FRVUZCd01DCkJnZ3JCZ0VGQlFjREFUQVBCZ05WSFJNQkFmOEVCVEFEQVFIL01CMEdBMVVkRGdRV0JCU25DVGdqVS95Uk5FUGUKRjRNbWpUTHcraUJDTURBTkJna3Foa2lHOXcwQkFRc0ZBQU9DQVFFQVlZcG85WVc4Nzl5WHRDSVNheXFPbVpvZgp4VGtSc3lWRzZEd2tWMG9tQTd1c0M2Z1lnZFVLRGM4V0RuWWZ2eHFIWkVLamNZUm9aZG16ckNxSjdUU05vdHpNCnF3T2xQNnMvU0Nka0Q2cUJiL0d5dkxnNWFNanUxaDNNRzIvT3dhTzcraGZUZCtyTlZTMVVWYVhYMjBNamxSMG8KV3YwWGVoTVlRMDBZRjFSKzYxTzFkRGdpZ29ZYVBzSzRlY2pGYzIzRjQwN1dDbzdWNVZKa2V3eDFKZTdDY0RuSAplaWFBb0I4YmQwcFBYaHpaYkIrN0ZQdFJ1Njg3cjB6ZHordkp1dW15SDYxQ2Y5djBoNmZEbU8wQjJTRUozZStjCjhRSzhOdnlrUFMzNlBic2M5dEpZbTUxVkYyTjladk9EU2Vqb3RvdVZGdzhTQVVFN3A0dDJ0NWpIQ2NGV0x3PT0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=
    namespace: a3ViZS1zeXN0ZW0=
    token: ZXlKaGJHY2lPaUpTVXpJMU5pSXNJbXRwWkNJNklrVkdURWROWWt4dWEyVlBRbDlsT0hvd1RtZ3plbko1ZG5wSGQwOXJjbkJPT0VaTFVUaGhZa1pzZVUwaWZRLmV5SnBjM01pT2lKcmRXSmxjbTVsZEdWekwzTmxjblpwWTJWaFkyTnZkVzUwSWl3aWEzVmlaWEp1WlhSbGN5NXBieTl6WlhKMmFXTmxZV05qYjNWdWRDOXVZVzFsYzNCaFkyVWlPaUpyZFdKbExYTjVjM1JsYlNJc0ltdDFZbVZ5Ym1WMFpYTXVhVzh2YzJWeWRtbGpaV0ZqWTI5MWJuUXZjMlZqY21WMExtNWhiV1VpT2lKaFpHMXBiaTExYzJWeUxYUnZhMlZ1SWl3aWEzVmlaWEp1WlhSbGN5NXBieTl6WlhKMmFXTmxZV05qYjNWdWRDOXpaWEoyYVdObExXRmpZMjkxYm5RdWJtRnRaU0k2SW1Ga2JXbHVMWFZ6WlhJaUxDSnJkV0psY201bGRHVnpMbWx2TDNObGNuWnBZMlZoWTJOdmRXNTBMM05sY25acFkyVXRZV05qYjNWdWRDNTFhV1FpT2lKbFl6bGxORFpqTUMxa09ERmxMVFJqTjJZdFltUXpaQzB5WW1ObU16TTRPRGswTVRBaUxDSnpkV0lpT2lKemVYTjBaVzA2YzJWeWRtbGpaV0ZqWTI5MWJuUTZhM1ZpWlMxemVYTjBaVzA2WVdSdGFXNHRkWE5sY2lKOS5JeXA5Y1MzV1JGT3dwd0pRNG9saFBhSkpvcEVPUWtGQlNfUzFlRW5SM3BoT3VXN3dtbTdaTC04T0w2RHB0N3FsdzZqS3IwQTMtMk9VRnBybzJIUGNxUlZYY3hMR3RrY0FHWDFMMTFUMTdBQUhHb2JHTlhyUXRobFVMY04yWUxfWFA4VW9BbjNiZk5ibzQ5c2c2MVVXdFVOSkdBVHR6eE5WSGdXYWtuLWJJY1lNcXMyVHgzLWlHcm5sT1dGR043RGlwMC1VNzlycHpVWk41MHRTeWhfQmtoTWRnV2gwQ2tjU19hV185ZDE1OWdDRXdRb0l6TU10QUZZRDRsa3d3OUF0aWREX1ZmblJsS2tBTTNGUy1vbDdhd3hXc2JBSUJCdTdQOG1UaFIxMmpBSkEzakNuVm9heWpKOWw3YWNkbUVfOFFOM1M4a0pDaUtTdjNaV1VtM1BndXc=
  kind: Secret
  metadata:
    annotations:
      kubernetes.io/service-account.name: admin-user
      kubernetes.io/service-account.uid: ec9e46c0-d81e-4c7f-bd3d-2bcf33889410
    creationTimestamp: "2025-11-23T03:15:01Z"
    name: admin-user-token
    namespace: kube-system
    resourceVersion: "415"
    uid: c32199f7-694b-45a4-a62b-a4a56b8f3407
  type: kubernetes.io/service-account-token
- apiVersion: v1
  data:
    cloud-config: ewogICJjbHVzdGVyX2lkIjogImZkNDExMjQ1LTI4NDctNGU3Ni04ZTMxLTQ4N2E5ZDMyM2IyNiIsCiAgInRva2VuIjogIk9ZN0dEWlFTUEZSR0w3RkROU0VXSUNZN0JPSEJGQVhDS1dJUSIKfQ==
  kind: Secret
  metadata:
    creationTimestamp: "2025-11-23T03:15:17Z"
    name: cluster-autoscaler-cloud-config
    namespace: kube-system
    resourceVersion: "851"
    uid: 59936958-8ef4-405c-9481-3ee587e40698
  type: Opaque
- apiVersion: v1
  data:
    api-key: T1k3R0RaUVNQRlJHTDdGRE5TRVdJQ1k3Qk9IQkZBWENLV0lR
  kind: Secret
  metadata:
    creationTimestamp: "2025-11-23T03:15:12Z"
    name: vultr-csi
    namespace: kube-system
    resourceVersion: "651"
    uid: 580e7812-9b98-415a-89ae-b064d3fed20f
  type: Opaque
kind: List
metadata:
  resourceVersion: ""
