apiVersion: v1
items:
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    creationTimestamp: "2025-11-23T03:15:00Z"
    name: admin-user
    namespace: kube-system
    resourceVersion: "409"
    uid: ec9e46c0-d81e-4c7f-bd3d-2bcf33889410
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    creationTimestamp: "2025-11-23T03:14:56Z"
    name: attachdetach-controller
    namespace: kube-system
    resourceVersion: "297"
    uid: 1d2aa24e-a20f-4acb-a34e-3e8e27a0f302
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    creationTimestamp: "2025-11-23T03:15:03Z"
    name: calico-cni-plugin
    namespace: kube-system
    resourceVersion: "428"
    uid: 9b5f26f1-1156-451a-a1de-e59c4e1a3e3e
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    creationTimestamp: "2025-11-23T03:15:02Z"
    name: calico-kube-controllers
    namespace: kube-system
    resourceVersion: "423"
    uid: 42c19dee-44a5-4b49-8a86-3fcf8cf56719
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    creationTimestamp: "2025-11-23T03:15:02Z"
    name: calico-node
    namespace: kube-system
    resourceVersion: "426"
    uid: c52d5e41-5a17-471c-91ae-ad786d52f842
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    creationTimestamp: "2025-11-23T03:14:54Z"
    name: certificate-controller
    namespace: kube-system
    resourceVersion: "283"
    uid: 074e11ee-a330-4004-a700-60f3378a352d
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    creationTimestamp: "2025-11-23T03:15:16Z"
    labels:
      k8s-addon: cluster-autoscaler.addons.k8s.io
      k8s-app: cluster-autoscaler
    name: cluster-autoscaler
    namespace: kube-system
    resourceVersion: "830"
    uid: 84e48712-3c20-4151-816f-f7b1cdcb15af
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    creationTimestamp: "2025-11-23T03:14:56Z"
    name: clusterrole-aggregation-controller
    namespace: kube-system
    resourceVersion: "301"
    uid: fa7430a8-d2cc-4cac-a652-ab6e407d51d1
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    creationTimestamp: "2025-11-23T03:15:09Z"
    name: coredns
    namespace: kube-system
    resourceVersion: "580"
    uid: 8bd827f5-75e5-4991-9bbc-a4e1d9f23a99
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    creationTimestamp: "2025-11-23T03:14:57Z"
    name: cronjob-controller
    namespace: kube-system
    resourceVersion: "322"
    uid: 1289c8cc-9394-48ff-ade7-43726d959624
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    creationTimestamp: "2025-11-23T03:15:13Z"
    name: csi-vultr-controller-sa
    namespace: kube-system
    resourceVersion: "673"
    uid: 6c073864-f4a8-4b5f-be81-e315a701628b
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    creationTimestamp: "2025-11-23T03:15:13Z"
    name: csi-vultr-node-sa
    namespace: kube-system
    resourceVersion: "688"
    uid: aef1e786-f004-4de4-a25c-d83ab003066c
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    creationTimestamp: "2025-11-23T03:14:58Z"
    name: daemon-set-controller
    namespace: kube-system
    resourceVersion: "349"
    uid: 3da48581-7416-4050-b1d1-3081a365ec6e
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    creationTimestamp: "2025-11-23T03:15:00Z"
    name: default
    namespace: kube-system
    resourceVersion: "402"
    uid: 31fd4073-1cb9-43d7-ac2d-07113484903b
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    creationTimestamp: "2025-11-23T03:14:56Z"
    name: deployment-controller
    namespace: kube-system
    resourceVersion: "312"
    uid: 9bc2ffd4-314b-4687-a314-fedb59247281
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    creationTimestamp: "2025-11-23T03:14:59Z"
    name: disruption-controller
    namespace: kube-system
    resourceVersion: "351"
    uid: ab6d33a8-ecbb-457a-a17b-26525a8ab36c
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    creationTimestamp: "2025-11-23T03:14:55Z"
    name: endpoint-controller
    namespace: kube-system
    resourceVersion: "289"
    uid: 1df15425-b5e0-4b18-8931-095a2202710a
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    creationTimestamp: "2025-11-23T03:14:58Z"
    name: endpointslice-controller
    namespace: kube-system
    resourceVersion: "340"
    uid: 87fc16e2-a3e9-49cc-a089-7c1d82c07859
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    creationTimestamp: "2025-11-23T03:14:55Z"
    name: endpointslicemirroring-controller
    namespace: kube-system
    resourceVersion: "290"
    uid: a6eaca7d-d663-4f87-a88d-d8275c52036f
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    creationTimestamp: "2025-11-23T03:14:57Z"
    name: ephemeral-volume-controller
    namespace: kube-system
    resourceVersion: "327"
    uid: 6430f0cb-76f4-41c3-9592-5fc3b96919da
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    creationTimestamp: "2025-11-23T03:14:58Z"
    name: expand-controller
    namespace: kube-system
    resourceVersion: "345"
    uid: ee9f9d98-415f-4899-8ebd-03f976c80099
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    creationTimestamp: "2025-11-23T03:14:54Z"
    name: generic-garbage-collector
    namespace: kube-system
    resourceVersion: "281"
    uid: 5b88cf0a-1c2d-4d0b-a893-7444579f16b8
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    creationTimestamp: "2025-11-23T03:14:57Z"
    name: horizontal-pod-autoscaler
    namespace: kube-system
    resourceVersion: "335"
    uid: 4dd5fdd0-8a6f-4aec-b188-545f39ad947c
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    creationTimestamp: "2025-11-23T03:14:54Z"
    name: job-controller
    namespace: kube-system
    resourceVersion: "282"
    uid: b2cff4e9-95dd-4369-a69e-ae7f9642bdf5
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    creationTimestamp: "2025-11-23T03:15:10Z"
    labels:
      addonmanager.kubernetes.io/mode: Reconcile
      kubernetes.io/cluster-service: "true"
    name: konnectivity-agent
    namespace: kube-system
    resourceVersion: "609"
    uid: 5a61032b-4f75-4224-a270-cb89766d4e19
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    creationTimestamp: "2025-11-23T03:15:15Z"
    labels:
      addonmanager.kubernetes.io/mode: Reconcile
    name: kube-proxy
    namespace: kube-system
    resourceVersion: "799"
    uid: 5c1e9fff-499e-4036-8b8b-187959147ba4
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    creationTimestamp: "2025-11-23T03:14:54Z"
    name: legacy-service-account-token-cleaner
    namespace: kube-system
    resourceVersion: "276"
    uid: 1adc41ba-e30a-4f4c-8900-9f70836137ba
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    creationTimestamp: "2025-11-23T03:14:56Z"
    name: namespace-controller
    namespace: kube-system
    resourceVersion: "309"
    uid: 79f73319-332f-483c-a1b9-be00b14fd41e
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    creationTimestamp: "2025-11-23T03:14:54Z"
    name: node-controller
    namespace: kube-system
    resourceVersion: "280"
    uid: 8cbec4b6-3b15-4af0-b4fe-6e70948e4309
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    creationTimestamp: "2025-11-23T03:14:55Z"
    name: persistent-volume-binder
    namespace: kube-system
    resourceVersion: "284"
    uid: 3d8b1d88-3b52-48ce-ba25-6561a3023c9e
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    creationTimestamp: "2025-11-23T03:14:57Z"
    name: pod-garbage-collector
    namespace: kube-system
    resourceVersion: "334"
    uid: 33952413-5000-41b2-bcda-0b7aeeb50064
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    creationTimestamp: "2025-11-23T03:14:55Z"
    name: pv-protection-controller
    namespace: kube-system
    resourceVersion: "288"
    uid: e799fa7d-a36c-48d5-b182-f3125a0e0fc9
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    creationTimestamp: "2025-11-23T03:14:59Z"
    name: pvc-protection-controller
    namespace: kube-system
    resourceVersion: "355"
    uid: 33f67cef-bc10-4ddd-a972-90b7fa114137
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    creationTimestamp: "2025-11-23T03:14:58Z"
    name: replicaset-controller
    namespace: kube-system
    resourceVersion: "342"
    uid: 58bdb6e1-00d2-45b2-bae8-e0198e6ca552
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    creationTimestamp: "2025-11-23T03:14:55Z"
    name: replication-controller
    namespace: kube-system
    resourceVersion: "291"
    uid: a9748e93-3f0e-40cc-af9b-9d17c5b86946
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    creationTimestamp: "2025-11-23T03:14:54Z"
    name: resource-claim-controller
    namespace: kube-system
    resourceVersion: "278"
    uid: 0758634a-029d-4283-9f1d-c97df474f48d
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    creationTimestamp: "2025-11-23T03:14:55Z"
    name: resourcequota-controller
    namespace: kube-system
    resourceVersion: "294"
    uid: d59ba8ee-686f-41c1-b705-316d94a62aea
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    creationTimestamp: "2025-11-23T03:14:56Z"
    name: root-ca-cert-publisher
    namespace: kube-system
    resourceVersion: "305"
    uid: f7cd17b2-506c-4a51-af04-612baf7da746
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    creationTimestamp: "2025-11-23T03:14:58Z"
    name: service-account-controller
    namespace: kube-system
    resourceVersion: "341"
    uid: 5651c29a-58c5-4b88-af89-36d132bf2ebe
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    creationTimestamp: "2025-11-23T03:14:54Z"
    name: service-cidrs-controller
    namespace: kube-system
    resourceVersion: "279"
    uid: 08be1780-3769-488c-920f-fa68f20f94b1
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    creationTimestamp: "2025-11-23T03:14:59Z"
    name: statefulset-controller
    namespace: kube-system
    resourceVersion: "354"
    uid: ea365edf-e76d-4df9-831e-2af55b12a9d8
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    creationTimestamp: "2025-11-23T03:14:54Z"
    name: ttl-after-finished-controller
    namespace: kube-system
    resourceVersion: "275"
    uid: 4edae11c-9600-4671-975a-4034ade12041
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    creationTimestamp: "2025-11-23T03:14:57Z"
    name: ttl-controller
    namespace: kube-system
    resourceVersion: "338"
    uid: 415d0509-cc34-49e9-8103-9f9ede097c97
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    creationTimestamp: "2025-11-23T03:14:58Z"
    name: validatingadmissionpolicy-status-controller
    namespace: kube-system
    resourceVersion: "346"
    uid: 71d3a8f7-3ea7-4e8d-bf71-ea7ce387e978
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    creationTimestamp: "2025-11-23T03:14:54Z"
    name: volumeattributesclass-protection-controller
    namespace: kube-system
    resourceVersion: "277"
    uid: bc77e60e-208c-4c9c-89a0-81eac272a311
kind: List
metadata:
  resourceVersion: ""
