apiVersion: v1
items:
- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    annotations:
      volume.beta.kubernetes.io/storage-provisioner: block.csi.vultr.com
      volume.kubernetes.io/storage-provisioner: block.csi.vultr.com
    creationTimestamp: "2025-11-23T19:31:48Z"
    finalizers:
    - kubernetes.io/pvc-protection
    labels:
      alertmanager: prometheus-kube-prometheus-alertmanager
      app.kubernetes.io/instance: prometheus-kube-prometheus-alertmanager
      app.kubernetes.io/managed-by: prometheus-operator
      app.kubernetes.io/name: alertmanager
    name: alertmanager-prometheus-kube-prometheus-alertmanager-db-alertmanager-prometheus-kube-prometheus-alertmanager-0
    namespace: monitoring
    resourceVersion: "157290"
    uid: 0cdf0479-ca4c-4333-a33d-bb99a9bdfd5a
  spec:
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 5Gi
    storageClassName: vultr-block-storage-hdd
    volumeMode: Filesystem
  status:
    phase: Pending
kind: List
metadata:
  resourceVersion: ""
